current:
  namespace: project_dev

server:
  port: 8101

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8845,http://localhost:8847,http://localhost:8849
        namespace: namespace_dev
        group: project_business

